version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: s16z-pms-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: s16z_pms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - s16z-pms-network

  redis:
    image: redis:7-alpine
    container_name: s16z-pms-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - s16z-pms-network

volumes:
  postgres_data:
  redis_data:

networks:
  s16z-pms-network:
    driver: bridge
